service: general-chatgpt-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1  # Default region, can be overridden with --region flag
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    PORT: 8080
    # Environment variables will be loaded from .env.${opt:stage, 'dev'} file
    # For sensitive values, use AWS SSM Parameter Store:
    # OPENAI_API_KEY: ${ssm:/my-app/${opt:stage, 'dev'}/api-secret~true}
    OPENAI_API_KEY: ${opt:stage, 'dev'}
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

# Dotenv plugin configuration
custom:
  dotenv:
    path: ./.env.${opt:stage, 'dev'}
    include:
      - NODE_ENV
      - PORT
      - OPENAI_API_KEY
      - DATABASE_URL
      # Add other environment variables you want to expose
  serverless-offline:
    httpPort: 3000

package:
  patterns:
    - '!node_modules/.cache/**'
    - '!.git/**'
    - '!frontend/**'
    - '!.env'
    - '!.env.*'
    - '!README.md'
    - '!package-lock.json'
    - '!coverage/**'
    - '!backend/**'
    - 'dist/**'
    - 'node_modules/**'