service: general-chatgpt-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    # Add any other environment variables your app needs
  
plugins:
  - serverless-offline

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  serverless-offline:
    httpPort: 3000
    
package:
  patterns:
    - '!node_modules/.cache/**'
    - '!.git/**'
    - '!frontend/**'
    - '!.env'
    - '!.env.*'
    - '!README.md'
    - '!package-lock.json'
    - '!coverage/**'
    - '!backend/**'
    - 'dist/**'
    - 'node_modules/**' 